# Generated by Django 6.1.1 on 2026-09-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Raw response payload from the payment provider",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
