# Generated by Django 6.1.1 on 2026-09-10 17:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="order",
            name="order_customer_address_consistency",
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_address",
            field=models.TextField(
                default="",
                help_text="Final delivery address at the time of order placement.",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("delivery_address__isnull", False),
                    models.Q(("delivery_address", ""), _negated=True),
                    ("email__isnull", False),
                    models.Q(("email", ""), _negated=True),
                    ("user_name__isnull", False),
                    models.Q(("user_name", ""), _negated=True),
                    ("user_phone__isnull", False),
                    models.Q(("user_phone", ""), _negated=True),
                ),
                name="order_fields_must_be_filled",
            ),
        ),
        migrations.RemoveField(
            model_name="order",
            name="guest_address",
        ),
    ]
