# Generated by Django 6.1.1 on 2026-09-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_remove_order_order_customer_address_consistency_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="fabric",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="fabric_composition_eng",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="fabric_composition_ua",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
