# Generated by Django 6.1.1 on 2026-09-08 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('discount_percent', models.PositiveSmallIntegerField(default=0)),
                ('price_uah', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_bestseller', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=False)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('discount_percent__lte', 100)), name='product_discount_lte_100')],
            },
        ),
        migrations.CreateModel(
            name='ProductFabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.fabric')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product', 'fabric'), name='unique_product_fabric')],
            },
        ),
    ]
