# Generated by Django 6.1.1 on 2026-09-10 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hex_code', models.CharField(blank=True, max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='productfabric',
            name='unique_product_fabric',
        ),
        migrations.AddField(
            model_name='product',
            name='fabric_composition',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productcolor',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.color'),
        ),
        migrations.AddField(
            model_name='productcolor',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='products.product'),
        ),
        migrations.RemoveField(
            model_name='productfabric',
            name='fabric',
        ),
        migrations.RemoveField(
            model_name='productfabric',
            name='product',
        ),
        migrations.DeleteModel(
            name='Fabric',
        ),
        migrations.DeleteModel(
            name='ProductFabric',
        ),
    ]
