# Generated by Django 6.1.1 on 2026-09-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_color_productcolor_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('order', 0)), fields=('product',), name='unique_main_image_per_product'),
        ),
    ]
