# Generated by Django 6.1.1 on 2026-09-10 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productimage_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='size_guides/')),
                ('description', models.TextField(blank=True)),
                ('product_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='size_guide', to='products.producttype')),
            ],
        ),
    ]
