# Generated by Django 6.1.1 on 2026-09-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_sizeguide'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_collection',
            field=models.BooleanField(default=False),
        ),
    ]
