# Generated by Django 6.1.1 on 2026-09-10 13:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_new_collection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='new_collection',
            new_name='is_new_collection',
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
