# Generated by Django 6.1.1 on 2026-09-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_new_collection_product_is_new_collection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fabric_composition',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sizeguide',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='description_eng',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ua',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fabric_composition_eng',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='fabric_composition_ua',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='producttype',
            name='name_eng',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producttype',
            name='name_ua',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sizeguide',
            name='description_eng',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sizeguide',
            name='description_ua',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
