# Generated by Django 6.1.1 on 2026-09-12 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_fabric_remove_product_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description_ua', models.TextField(blank=True)),
                ('description_eng', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='sizeguide',
            options={'verbose_name': 'Size guide', 'verbose_name_plural': 'Size guide'},
        ),
        migrations.RemoveField(
            model_name='sizeguide',
            name='product_type',
        ),
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.collection'),
        ),
    ]
