# Generated by Django 6.1.1 on 2026-09-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_collection_alter_sizeguide_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='slug',
            field=models.SlugField(default='default-collection', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
